"Resource/UI/MainMenuOverride.res"
{
    "SafeMode"
    {
        "ScrollingPanel"
        {
            "ContentPanel"
            {
                "Colors"
                {
                    "Buttons"
                    {
                        "Positive"
                        {
                            "ButtonContainer"
                            {
                                "1"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "1"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor1_60"
                                    "armedbgcolor_override"         "FragCColor1_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_1"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                }
                                "2"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "2"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor2_60"
                                    "armedbgcolor_override"         "FragCColor2_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_2"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "1"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "3"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "3"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor3_60"
                                    "armedbgcolor_override"         "FragCColor3_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_3"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "2"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "4"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "4"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor4_60"
                                    "armedbgcolor_override"         "FragCColor4_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_4"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "3"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "5"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "5"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor5_60"
                                    "armedbgcolor_override"         "FragCColor5_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_5"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "4"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "6"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "6"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor6_60"
                                    "armedbgcolor_override"         "FragCColor6_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_6"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "5"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "7"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "7"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor7_60"
                                    "armedbgcolor_override"         "FragCColor7_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_7"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "6"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "8"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "8"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor8_60"
                                    "armedbgcolor_override"         "FragCColor8_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_8"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "7"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "9"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "9"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor9_60"
                                    "armedbgcolor_override"         "FragCColor9_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_9"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "8"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "10"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "10"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor10_60"
                                    "armedbgcolor_override"         "FragCColor10_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_10"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "9"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "11"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "11"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor11_60"
                                    "armedbgcolor_override"         "FragCColor11_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_11"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "10"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "12"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "12"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor12_60"
                                    "armedbgcolor_override"         "FragCColor12_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_12"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "11"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "13"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "13"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor13_60"
                                    "armedbgcolor_override"         "FragCColor13_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_13"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "12"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "14"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "14"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor14_60"
                                    "armedbgcolor_override"         "FragCColor14_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_14"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "13"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "15"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "15"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor15_60"
                                    "armedbgcolor_override"         "FragCColor15_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_15"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "14"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "16"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "16"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor16_60"
                                    "armedbgcolor_override"         "FragCColor16_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_16"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "15"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "17"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "17"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor17_60"
                                    "armedbgcolor_override"         "FragCColor17_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_17"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "16"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "18"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "18"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor18_60"
                                    "armedbgcolor_override"         "FragCColor18_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_18"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "17"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "19"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "19"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor19_60"
                                    "armedbgcolor_override"         "FragCColor19_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_19"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "18"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "20"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "20"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor20_60"
                                    "armedbgcolor_override"         "FragCColor20_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_20"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "19"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "21"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "21"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor21_60"
                                    "armedbgcolor_override"         "FragCColor21_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_21"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "20"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "22"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "22"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor22_60"
                                    "armedbgcolor_override"         "FragCColor22_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_22"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "21"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "23"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "23"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor23_60"
                                    "armedbgcolor_override"         "FragCColor23_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_23"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "22"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "24"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "24"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor24_60"
                                    "armedbgcolor_override"         "FragCColor24_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_24"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "23"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "25"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "25"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor25_60"
                                    "armedbgcolor_override"         "FragCColor25_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_25"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "24"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "26"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "26"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor26_60"
                                    "armedbgcolor_override"         "FragCColor26_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_26"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "25"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "27"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "27"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor27_60"
                                    "armedbgcolor_override"         "FragCColor27_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_27"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "26"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "28"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "28"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor28_60"
                                    "armedbgcolor_override"         "FragCColor28_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_28"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "27"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "29"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "29"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor29_60"
                                    "armedbgcolor_override"         "FragCColor29_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_29"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "28"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "30"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "30"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor30_60"
                                    "armedbgcolor_override"         "FragCColor30_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_30"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "29"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "31"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "31"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor31_60"
                                    "armedbgcolor_override"         "FragCColor31_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_31"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "30"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "32"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "32"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor32_60"
                                    "armedbgcolor_override"         "FragCColor32_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_32"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "31"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "33"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "33"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor33_60"
                                    "armedbgcolor_override"         "FragCColor33_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_33"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "32"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "34"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "34"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor34_60"
                                    "armedbgcolor_override"         "FragCColor34_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_34"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "33"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "35"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "35"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor35_60"
                                    "armedbgcolor_override"         "FragCColor35_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_35"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "34"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                                "36"
                                {
                                    "ControlName"                   "CExButton"
                                    "fieldName"                     "36"
                                    "xpos"                          "0"
                                    "ypos"                          "0"
                                    "wide"                          "5"
                                    "tall"                          "f0"
                                    "proportionaltoparent"          "1"
                                    "defaultbgcolor_override"       "FragCColor36_60"
                                    "armedbgcolor_override"         "FragCColor36_100"
                                    "border_armed"                  "FragColorSelection"
                                    "labelText"                     ""
                                    "command"                       "engine frag_cpositive_36"
                                    "actionsignallevel"             "8"
                                    "sound_depressed"               "ui/buttonclick.wav"
                                    "sound_released"                "ui/buttonclickrelease.wav"
                                    "pin_to_sibling"                "35"
                                    "pin_corner_to_sibling"         "PIN_TOPLEFT"
                                    "pin_to_sibling_corner"         "PIN_TOPRIGHT"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}