"Resource/UI/MainMenuOverride.res"
{
"SafeMode"
{
"ScrollingPanel"
{
"ContentPanel"
{
"Colors"
{
"Buttons"
{
"Primary"
{
"ButtonContainer"
{
"1"
{
"ControlName" "CExButton"
"fieldName" "1"
"xpos" "0"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor1_100"
"armedbgcolor_override" "FragCColor1_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=1"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"2"
{
"ControlName" "CExButton"
"fieldName" "2"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor2_100"
"armedbgcolor_override" "FragCColor2_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=2"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "1"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"3"
{
"ControlName" "CExButton"
"fieldName" "3"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor3_100"
"armedbgcolor_override" "FragCColor3_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=3"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "2"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"4"
{
"ControlName" "CExButton"
"fieldName" "4"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor4_100"
"armedbgcolor_override" "FragCColor4_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=4"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "3"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"5"
{
"ControlName" "CExButton"
"fieldName" "5"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor5_100"
"armedbgcolor_override" "FragCColor5_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=5"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "4"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"6"
{
"ControlName" "CExButton"
"fieldName" "6"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor6_100"
"armedbgcolor_override" "FragCColor6_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=6"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "5"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"7"
{
"ControlName" "CExButton"
"fieldName" "7"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor7_100"
"armedbgcolor_override" "FragCColor7_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=7"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "6"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"8"
{
"ControlName" "CExButton"
"fieldName" "8"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor8_100"
"armedbgcolor_override" "FragCColor8_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=8"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "7"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"9"
{
"ControlName" "CExButton"
"fieldName" "9"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor9_100"
"armedbgcolor_override" "FragCColor9_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=9"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "8"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"10"
{
"ControlName" "CExButton"
"fieldName" "10"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor10_100"
"armedbgcolor_override" "FragCColor10_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=10"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "9"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"11"
{
"ControlName" "CExButton"
"fieldName" "11"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor11_100"
"armedbgcolor_override" "FragCColor11_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=11"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "10"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"12"
{
"ControlName" "CExButton"
"fieldName" "12"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor12_100"
"armedbgcolor_override" "FragCColor12_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=12"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "11"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"13"
{
"ControlName" "CExButton"
"fieldName" "13"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor13_100"
"armedbgcolor_override" "FragCColor13_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=13"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "12"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"14"
{
"ControlName" "CExButton"
"fieldName" "14"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor14_100"
"armedbgcolor_override" "FragCColor14_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=14"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "13"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"15"
{
"ControlName" "CExButton"
"fieldName" "15"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor15_100"
"armedbgcolor_override" "FragCColor15_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=15"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "14"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"16"
{
"ControlName" "CExButton"
"fieldName" "16"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor16_100"
"armedbgcolor_override" "FragCColor16_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=16"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "15"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"17"
{
"ControlName" "CExButton"
"fieldName" "17"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor17_100"
"armedbgcolor_override" "FragCColor17_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=17"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "16"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"18"
{
"ControlName" "CExButton"
"fieldName" "18"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor18_100"
"armedbgcolor_override" "FragCColor18_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=18"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "17"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"19"
{
"ControlName" "CExButton"
"fieldName" "19"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor19_100"
"armedbgcolor_override" "FragCColor19_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=19"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "18"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"20"
{
"ControlName" "CExButton"
"fieldName" "20"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor20_100"
"armedbgcolor_override" "FragCColor20_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=20"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "19"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"21"
{
"ControlName" "CExButton"
"fieldName" "21"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor21_100"
"armedbgcolor_override" "FragCColor21_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=21"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "20"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"22"
{
"ControlName" "CExButton"
"fieldName" "22"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor22_100"
"armedbgcolor_override" "FragCColor22_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=22"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "21"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"23"
{
"ControlName" "CExButton"
"fieldName" "23"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor23_100"
"armedbgcolor_override" "FragCColor23_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=23"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "22"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"24"
{
"ControlName" "CExButton"
"fieldName" "24"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor24_100"
"armedbgcolor_override" "FragCColor24_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=24"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "23"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"25"
{
"ControlName" "CExButton"
"fieldName" "25"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor25_100"
"armedbgcolor_override" "FragCColor25_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=25"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "24"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"26"
{
"ControlName" "CExButton"
"fieldName" "26"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor26_100"
"armedbgcolor_override" "FragCColor26_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=26"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "25"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"27"
{
"ControlName" "CExButton"
"fieldName" "27"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor27_100"
"armedbgcolor_override" "FragCColor27_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=27"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "26"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"28"
{
"ControlName" "CExButton"
"fieldName" "28"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor28_100"
"armedbgcolor_override" "FragCColor28_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=28"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "27"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"29"
{
"ControlName" "CExButton"
"fieldName" "29"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor29_100"
"armedbgcolor_override" "FragCColor29_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=29"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "28"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"30"
{
"ControlName" "CExButton"
"fieldName" "30"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor30_100"
"armedbgcolor_override" "FragCColor30_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=30"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "29"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"31"
{
"ControlName" "CExButton"
"fieldName" "31"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor31_100"
"armedbgcolor_override" "FragCColor31_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=31"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "30"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"32"
{
"ControlName" "CExButton"
"fieldName" "32"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor32_100"
"armedbgcolor_override" "FragCColor32_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=32"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "31"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"33"
{
"ControlName" "CExButton"
"fieldName" "33"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor33_100"
"armedbgcolor_override" "FragCColor33_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=33"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "32"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"34"
{
"ControlName" "CExButton"
"fieldName" "34"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor34_100"
"armedbgcolor_override" "FragCColor34_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=34"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "33"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"35"
{
"ControlName" "CExButton"
"fieldName" "35"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor35_100"
"armedbgcolor_override" "FragCColor35_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=35"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "34"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"36"
{
"ControlName" "CExButton"
"fieldName" "36"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor36_100"
"armedbgcolor_override" "FragCColor36_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=36"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "35"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"37"
{
"ControlName" "CExButton"
"fieldName" "37"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor37_100"
"armedbgcolor_override" "FragCColor37_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=37"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "36"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"38"
{
"ControlName" "CExButton"
"fieldName" "38"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor38_100"
"armedbgcolor_override" "FragCColor38_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=38"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "37"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"39"
{
"ControlName" "CExButton"
"fieldName" "39"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor39_100"
"armedbgcolor_override" "FragCColor39_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=39"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "38"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"40"
{
"ControlName" "CExButton"
"fieldName" "40"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor40_100"
"armedbgcolor_override" "FragCColor40_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=40"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "39"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"41"
{
"ControlName" "CExButton"
"fieldName" "41"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor41_100"
"armedbgcolor_override" "FragCColor41_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=41"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "40"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"42"
{
"ControlName" "CExButton"
"fieldName" "42"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor42_100"
"armedbgcolor_override" "FragCColor42_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=42"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "41"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"43"
{
"ControlName" "CExButton"
"fieldName" "43"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor43_100"
"armedbgcolor_override" "FragCColor43_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=43"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "42"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"44"
{
"ControlName" "CExButton"
"fieldName" "44"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor44_100"
"armedbgcolor_override" "FragCColor44_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=44"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "43"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"45"
{
"ControlName" "CExButton"
"fieldName" "45"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor45_100"
"armedbgcolor_override" "FragCColor45_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=45"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "44"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"46"
{
"ControlName" "CExButton"
"fieldName" "46"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor46_100"
"armedbgcolor_override" "FragCColor46_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=46"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "45"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
"47"
{
"ControlName" "CExButton"
"fieldName" "47"
"xpos" "1"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "FragCColor47_100"
"armedbgcolor_override" "FragCColor47_100"
"border_armed" "FragColorSelection"
"labelText" ""
"command" "engine frag_cprimary=47"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
"pin_to_sibling" "46"
"pin_corner_to_sibling" "PIN_TOPLEFT"
"pin_to_sibling_corner" "PIN_TOPRIGHT"
}
}
}
}
}
}
}
}
}
