"Resource/UI/MainMenuOverride.res"
{
"SafeMode"
{
"ScrollingPanel"
{
"ContentPanel"
{
"Colors"
{
"Sections"
{
"Negative"
{
"ButtonContainer"
{
"1"
{
"ControlName" "CExButton"
"fieldName" "1"
"xpos" "0"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=1"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"2"
{
"ControlName" "CExButton"
"fieldName" "2"
"xpos" "3"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=2"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"3"
{
"ControlName" "CExButton"
"fieldName" "3"
"xpos" "6"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=3"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"4"
{
"ControlName" "CExButton"
"fieldName" "4"
"xpos" "9"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=4"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"5"
{
"ControlName" "CExButton"
"fieldName" "5"
"xpos" "12"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=5"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"6"
{
"ControlName" "CExButton"
"fieldName" "6"
"xpos" "15"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=6"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"7"
{
"ControlName" "CExButton"
"fieldName" "7"
"xpos" "18"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=7"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"8"
{
"ControlName" "CExButton"
"fieldName" "8"
"xpos" "21"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=8"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"9"
{
"ControlName" "CExButton"
"fieldName" "9"
"xpos" "24"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=9"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"10"
{
"ControlName" "CExButton"
"fieldName" "10"
"xpos" "27"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=10"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"11"
{
"ControlName" "CExButton"
"fieldName" "11"
"xpos" "30"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=11"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"12"
{
"ControlName" "CExButton"
"fieldName" "12"
"xpos" "33"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=12"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"13"
{
"ControlName" "CExButton"
"fieldName" "13"
"xpos" "36"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=13"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"14"
{
"ControlName" "CExButton"
"fieldName" "14"
"xpos" "39"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=14"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"15"
{
"ControlName" "CExButton"
"fieldName" "15"
"xpos" "42"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=15"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"16"
{
"ControlName" "CExButton"
"fieldName" "16"
"xpos" "45"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=16"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"17"
{
"ControlName" "CExButton"
"fieldName" "17"
"xpos" "48"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=17"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"18"
{
"ControlName" "CExButton"
"fieldName" "18"
"xpos" "51"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=18"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"19"
{
"ControlName" "CExButton"
"fieldName" "19"
"xpos" "54"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=19"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"20"
{
"ControlName" "CExButton"
"fieldName" "20"
"xpos" "57"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=20"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"21"
{
"ControlName" "CExButton"
"fieldName" "21"
"xpos" "60"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=21"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"22"
{
"ControlName" "CExButton"
"fieldName" "22"
"xpos" "63"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=22"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"23"
{
"ControlName" "CExButton"
"fieldName" "23"
"xpos" "66"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=23"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"24"
{
"ControlName" "CExButton"
"fieldName" "24"
"xpos" "69"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=24"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"25"
{
"ControlName" "CExButton"
"fieldName" "25"
"xpos" "72"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=25"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"26"
{
"ControlName" "CExButton"
"fieldName" "26"
"xpos" "75"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=26"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"27"
{
"ControlName" "CExButton"
"fieldName" "27"
"xpos" "78"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=27"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"28"
{
"ControlName" "CExButton"
"fieldName" "28"
"xpos" "81"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=28"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"29"
{
"ControlName" "CExButton"
"fieldName" "29"
"xpos" "84"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=29"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"30"
{
"ControlName" "CExButton"
"fieldName" "30"
"xpos" "87"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=30"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"31"
{
"ControlName" "CExButton"
"fieldName" "31"
"xpos" "90"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=31"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"32"
{
"ControlName" "CExButton"
"fieldName" "32"
"xpos" "93"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=32"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"33"
{
"ControlName" "CExButton"
"fieldName" "33"
"xpos" "96"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=33"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"34"
{
"ControlName" "CExButton"
"fieldName" "34"
"xpos" "99"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=34"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"35"
{
"ControlName" "CExButton"
"fieldName" "35"
"xpos" "102"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=35"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"36"
{
"ControlName" "CExButton"
"fieldName" "36"
"xpos" "105"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=36"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"37"
{
"ControlName" "CExButton"
"fieldName" "37"
"xpos" "108"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=37"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"38"
{
"ControlName" "CExButton"
"fieldName" "38"
"xpos" "111"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=38"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"39"
{
"ControlName" "CExButton"
"fieldName" "39"
"xpos" "114"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=39"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"40"
{
"ControlName" "CExButton"
"fieldName" "40"
"xpos" "117"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=40"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"41"
{
"ControlName" "CExButton"
"fieldName" "41"
"xpos" "120"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=41"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"42"
{
"ControlName" "CExButton"
"fieldName" "42"
"xpos" "123"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=42"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"43"
{
"ControlName" "CExButton"
"fieldName" "43"
"xpos" "126"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=43"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"44"
{
"ControlName" "CExButton"
"fieldName" "44"
"xpos" "129"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=44"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"45"
{
"ControlName" "CExButton"
"fieldName" "45"
"xpos" "132"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=45"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"46"
{
"ControlName" "CExButton"
"fieldName" "46"
"xpos" "135"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=46"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"47"
{
"ControlName" "CExButton"
"fieldName" "47"
"xpos" "138"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=47"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"48"
{
"ControlName" "CExButton"
"fieldName" "48"
"xpos" "141"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=48"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"49"
{
"ControlName" "CExButton"
"fieldName" "49"
"xpos" "144"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=49"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"50"
{
"ControlName" "CExButton"
"fieldName" "50"
"xpos" "147"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=50"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"51"
{
"ControlName" "CExButton"
"fieldName" "51"
"xpos" "150"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=51"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"52"
{
"ControlName" "CExButton"
"fieldName" "52"
"xpos" "153"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=52"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"53"
{
"ControlName" "CExButton"
"fieldName" "53"
"xpos" "156"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=53"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"54"
{
"ControlName" "CExButton"
"fieldName" "54"
"xpos" "159"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=54"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"55"
{
"ControlName" "CExButton"
"fieldName" "55"
"xpos" "162"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=55"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"56"
{
"ControlName" "CExButton"
"fieldName" "56"
"xpos" "165"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=56"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"57"
{
"ControlName" "CExButton"
"fieldName" "57"
"xpos" "168"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=57"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"58"
{
"ControlName" "CExButton"
"fieldName" "58"
"xpos" "171"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=58"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"59"
{
"ControlName" "CExButton"
"fieldName" "59"
"xpos" "174"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=59"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
"60"
{
"ControlName" "CExButton"
"fieldName" "60"
"xpos" "177"
"ypos" "0"
"wide" "3"
"tall" "f0"
"proportionaltoparent" "1"
"defaultbgcolor_override" "Blank"
"armedbgcolor_override" "FragPanelTransparentDark60"
"labelText" ""
"command" "engine frag_cnegative=60"
"actionsignallevel" "8"
"sound_depressed" "ui/buttonclick.wav"
"sound_released" "ui/buttonclickrelease.wav"
}
}
}
}
}
}
}
}
}
